name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update project folder
        run: |
          set -e
          cd /home/Luffy/.config/quickshell/caelestia
          git status
          git fetch --all
          git pull

      - name: Restart shell
        run: |
          export DISPLAY=:0
          export XDG_RUNTIME_DIR=/run/user/1000
          qs -c caelestia kill  
      - name: start shell
        run: |
          systemctl --machine=Luffy@.host --user restart quickshell.service